/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Hattmakarsystem;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.plaf.basic.BasicTabbedPaneUI;
/**
 *
 * @author Lucas
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    private JButton[] knappar;
    public GUI() {
        initComponents();
        knappGenerering();
        knappVisning1();
        sdf();
        gomtabs();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenyValjP = new javax.swing.JPanel();
        OrderValjP = new javax.swing.JPanel();
        HuvudPanel = new javax.swing.JTabbedPane();
        KundjP = new javax.swing.JPanel();
        OrderjP = new javax.swing.JPanel();
        HanteraKontojP = new javax.swing.JPanel();
        FraktsedeljP = new javax.swing.JPanel();
        OrdertF = new javax.swing.JTextField();
        OrderNummerLabel = new javax.swing.JLabel();
        OrderSokBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MenyValjP.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout MenyValjPLayout = new javax.swing.GroupLayout(MenyValjP);
        MenyValjP.setLayout(MenyValjPLayout);
        MenyValjPLayout.setHorizontalGroup(
            MenyValjPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 182, Short.MAX_VALUE)
        );
        MenyValjPLayout.setVerticalGroup(
            MenyValjPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        OrderValjP.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout OrderValjPLayout = new javax.swing.GroupLayout(OrderValjP);
        OrderValjP.setLayout(OrderValjPLayout);
        OrderValjPLayout.setHorizontalGroup(
            OrderValjPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 161, Short.MAX_VALUE)
        );
        OrderValjPLayout.setVerticalGroup(
            OrderValjPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        HuvudPanel.setBackground(new java.awt.Color(255, 255, 255));
        HuvudPanel.setName(""); // NOI18N

        KundjP.setBackground(new java.awt.Color(204, 204, 204));
        KundjP.setEnabled(false);

        javax.swing.GroupLayout KundjPLayout = new javax.swing.GroupLayout(KundjP);
        KundjP.setLayout(KundjPLayout);
        KundjPLayout.setHorizontalGroup(
            KundjPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 703, Short.MAX_VALUE)
        );
        KundjPLayout.setVerticalGroup(
            KundjPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        HuvudPanel.addTab("Lägg TIll/Välj Kund", KundjP);

        OrderjP.setEnabled(false);

        javax.swing.GroupLayout OrderjPLayout = new javax.swing.GroupLayout(OrderjP);
        OrderjP.setLayout(OrderjPLayout);
        OrderjPLayout.setHorizontalGroup(
            OrderjPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 703, Short.MAX_VALUE)
        );
        OrderjPLayout.setVerticalGroup(
            OrderjPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        HuvudPanel.addTab("Lägg Order", OrderjP);

        HanteraKontojP.setEnabled(false);

        javax.swing.GroupLayout HanteraKontojPLayout = new javax.swing.GroupLayout(HanteraKontojP);
        HanteraKontojP.setLayout(HanteraKontojPLayout);
        HanteraKontojPLayout.setHorizontalGroup(
            HanteraKontojPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 703, Short.MAX_VALUE)
        );
        HanteraKontojPLayout.setVerticalGroup(
            HanteraKontojPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        HuvudPanel.addTab("Hantera Konton", HanteraKontojP);

        FraktsedeljP.setEnabled(false);

        OrderNummerLabel.setText("Order nummer");

        OrderSokBtn.setText("Sök");

        javax.swing.GroupLayout FraktsedeljPLayout = new javax.swing.GroupLayout(FraktsedeljP);
        FraktsedeljP.setLayout(FraktsedeljPLayout);
        FraktsedeljPLayout.setHorizontalGroup(
            FraktsedeljPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FraktsedeljPLayout.createSequentialGroup()
                .addGroup(FraktsedeljPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FraktsedeljPLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(OrderNummerLabel))
                    .addGroup(FraktsedeljPLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(FraktsedeljPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FraktsedeljPLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(OrderSokBtn))
                            .addComponent(OrdertF, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(582, Short.MAX_VALUE))
        );
        FraktsedeljPLayout.setVerticalGroup(
            FraktsedeljPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FraktsedeljPLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(OrderNummerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OrdertF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OrderSokBtn)
                .addContainerGap(564, Short.MAX_VALUE))
        );

        HuvudPanel.addTab("fraktsedel", FraktsedeljP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MenyValjP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(HuvudPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(OrderValjP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(OrderValjP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MenyValjP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(HuvudPanel))
                .addContainerGap())
        );

        HuvudPanel.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    private void knappGenerering()
    {
        
        int numberoftabs = HuvudPanel.getTabCount();
        knappar = new JButton[numberoftabs];
        for (int i = 0; i < numberoftabs; i++) {  
        final int index = i;
        knappar[i] = new JButton(HuvudPanel.getTitleAt(i));
        knappar[i].addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent e){
               HuvudPanel.setSelectedIndex(index);
            }
        });
            
            
        }
    }
    
    private void sdf()
    {
        for (int i = 0; i < HuvudPanel.getTabCount(); i++) {  
        final int index = i;
        
               HuvudPanel.setEnabledAt(index, false);
            
    }
    }
   
 private void knappVisning1()
    {
        int height = MenyValjP.getHeight();
    int knapparCount = knappar.length;
    int knappHeight = height / knapparCount;
    int yPosition = (height / knapparCount)/2-20;

    for (JButton button : knappar) {
        MenyValjP.add(button);
        button.setVisible(true);
        button.setSize(150, 40);
        button.setLocation(20, yPosition);

        yPosition += knappHeight;
    }
    }
    
    private void gomtabs()
    {
     HuvudPanel.setUI(new BasicTabbedPaneUI() {       @Override       protected int calculateTabAreaHeight(int tab_placement, int run_count, int max_tab_height) {                         return 0;       }   });
             }   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FraktsedeljP;
    private javax.swing.JPanel HanteraKontojP;
    private javax.swing.JTabbedPane HuvudPanel;
    private javax.swing.JPanel KundjP;
    private javax.swing.JPanel MenyValjP;
    private javax.swing.JLabel OrderNummerLabel;
    private javax.swing.JButton OrderSokBtn;
    private javax.swing.JPanel OrderValjP;
    private javax.swing.JPanel OrderjP;
    private javax.swing.JTextField OrdertF;
    // End of variables declaration//GEN-END:variables
}
