/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Hattmakarsystem;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.plaf.basic.BasicTabbedPaneUI;
/**
 *
 * @author Lucas
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    private JButton[] knappar;
    public GUI() {
        initComponents();
        knappGenerering();
        knappVisning1();
        DisableTabs();
        gomtabs();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenyValjP = new javax.swing.JPanel();
        OrderValjP = new javax.swing.JPanel();
        HuvudPanel = new javax.swing.JTabbedPane();
        KundjP = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        button1 = new java.awt.Button();
        jTextNamn = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextTelefon = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextAdress = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        OrderjP = new javax.swing.JPanel();
        HanteraKontojP = new javax.swing.JPanel();
        FraktsedeljP = new javax.swing.JPanel();
        OrdertF = new javax.swing.JTextField();
        OrderNummerLabel = new javax.swing.JLabel();
        OrderSokBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MenyValjP.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout MenyValjPLayout = new javax.swing.GroupLayout(MenyValjP);
        MenyValjP.setLayout(MenyValjPLayout);
        MenyValjPLayout.setHorizontalGroup(
            MenyValjPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 182, Short.MAX_VALUE)
        );
        MenyValjPLayout.setVerticalGroup(
            MenyValjPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        OrderValjP.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout OrderValjPLayout = new javax.swing.GroupLayout(OrderValjP);
        OrderValjP.setLayout(OrderValjPLayout);
        OrderValjPLayout.setHorizontalGroup(
            OrderValjPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 161, Short.MAX_VALUE)
        );
        OrderValjPLayout.setVerticalGroup(
            OrderValjPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        HuvudPanel.setBackground(new java.awt.Color(255, 255, 255));
        HuvudPanel.setName(""); // NOI18N

        KundjP.setBackground(new java.awt.Color(255, 255, 255));
        KundjP.setEnabled(false);

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        jLabel1.setText("Sök efter kund epost");

        button1.setLabel("Sök");

        jLabel2.setText("Namn");

        jLabel3.setText("Emailadress");

        jLabel4.setText("Telefonnummer");

        jLabel5.setText("Adress");

        jButton1.setText("Gå vidare med vald kund");

        jButton2.setText("Lägg till ny kund och gå vidare");

        jButton3.setText("Ändra kunduppgifter och gå vidare");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout KundjPLayout = new javax.swing.GroupLayout(KundjP);
        KundjP.setLayout(KundjPLayout);
        KundjPLayout.setHorizontalGroup(
            KundjPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KundjPLayout.createSequentialGroup()
                .addGroup(KundjPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(KundjPLayout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(jButton3))
                    .addGroup(KundjPLayout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KundjPLayout.createSequentialGroup()
                .addGroup(KundjPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(KundjPLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addGroup(KundjPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(KundjPLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(17, 17, 17)
                                .addComponent(jTextTelefon))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, KundjPLayout.createSequentialGroup()
                                .addGroup(KundjPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(40, 40, 40)
                                .addGroup(KundjPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(KundjPLayout.createSequentialGroup()
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jTextNamn)
                                    .addComponent(jTextEmail)))
                            .addGroup(KundjPLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                                .addGroup(KundjPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2)
                                    .addComponent(jTextAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(17, 17, 17))
                    .addGroup(KundjPLayout.createSequentialGroup()
                        .addGap(313, 313, 313)
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(KundjPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(52, 52, 52))
        );
        KundjPLayout.setVerticalGroup(
            KundjPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KundjPLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(KundjPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(KundjPLayout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(KundjPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(KundjPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(KundjPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(KundjPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(29, 29, 29))
        );

        HuvudPanel.addTab("Lägg TIll/Välj Kund", KundjP);

        OrderjP.setEnabled(false);

        javax.swing.GroupLayout OrderjPLayout = new javax.swing.GroupLayout(OrderjP);
        OrderjP.setLayout(OrderjPLayout);
        OrderjPLayout.setHorizontalGroup(
            OrderjPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 703, Short.MAX_VALUE)
        );
        OrderjPLayout.setVerticalGroup(
            OrderjPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        HuvudPanel.addTab("Lägg Order", OrderjP);

        HanteraKontojP.setEnabled(false);

        javax.swing.GroupLayout HanteraKontojPLayout = new javax.swing.GroupLayout(HanteraKontojP);
        HanteraKontojP.setLayout(HanteraKontojPLayout);
        HanteraKontojPLayout.setHorizontalGroup(
            HanteraKontojPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 703, Short.MAX_VALUE)
        );
        HanteraKontojPLayout.setVerticalGroup(
            HanteraKontojPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        HuvudPanel.addTab("Hantera Konton", HanteraKontojP);

        FraktsedeljP.setEnabled(false);

        OrderNummerLabel.setText("Order nummer");

        OrderSokBtn.setText("Sök");

        javax.swing.GroupLayout FraktsedeljPLayout = new javax.swing.GroupLayout(FraktsedeljP);
        FraktsedeljP.setLayout(FraktsedeljPLayout);
        FraktsedeljPLayout.setHorizontalGroup(
            FraktsedeljPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FraktsedeljPLayout.createSequentialGroup()
                .addGroup(FraktsedeljPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FraktsedeljPLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(OrderNummerLabel))
                    .addGroup(FraktsedeljPLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(FraktsedeljPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FraktsedeljPLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(OrderSokBtn))
                            .addComponent(OrdertF, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(582, Short.MAX_VALUE))
        );
        FraktsedeljPLayout.setVerticalGroup(
            FraktsedeljPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FraktsedeljPLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(OrderNummerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OrdertF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OrderSokBtn)
                .addContainerGap(564, Short.MAX_VALUE))
        );

        HuvudPanel.addTab("fraktsedel", FraktsedeljP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MenyValjP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(HuvudPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(OrderValjP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(OrderValjP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MenyValjP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(HuvudPanel))
                .addContainerGap())
        );

        HuvudPanel.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        DefaultListModel<String> listModel = Sok.sok(jTextField1.getText(), "kund", "email");
        jList1.setModel(listModel);
    }//GEN-LAST:event_jTextField1KeyReleased

    /**
     * @param args the command line arguments
     */
    private void knappGenerering()
    {
        
        int numberoftabs = HuvudPanel.getTabCount();
        knappar = new JButton[numberoftabs];
        for (int i = 0; i < numberoftabs; i++) {  
        final int index = i;
        knappar[i] = new JButton(HuvudPanel.getTitleAt(i));
        knappar[i].addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent e){
               HuvudPanel.setSelectedIndex(index);
            }
        });
            
            
        }
    }
    
    private void DisableTabs()
    {
        for (int i = 0; i < HuvudPanel.getTabCount(); i++) {  
        final int index = i;
        
               HuvudPanel.setEnabledAt(index, false);
            
    }
    }
   
 private void knappVisning1()
    {
        int height = MenyValjP.getHeight();
    int knapparCount = knappar.length;
    int knappHeight = height / knapparCount;
    int yPosition = (height / knapparCount)/2-20;

    for (JButton button : knappar) {
        MenyValjP.add(button);
        button.setVisible(true);
        button.setSize(150, 40);
        button.setLocation(20, yPosition);

        yPosition += knappHeight;
    }
    }
    
    private void gomtabs()
    {
     HuvudPanel.setUI(new BasicTabbedPaneUI() {       @Override       protected int calculateTabAreaHeight(int tab_placement, int run_count, int max_tab_height) {                         return 0;       }   });
             }   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FraktsedeljP;
    private javax.swing.JPanel HanteraKontojP;
    private javax.swing.JTabbedPane HuvudPanel;
    private javax.swing.JPanel KundjP;
    private javax.swing.JPanel MenyValjP;
    private javax.swing.JLabel OrderNummerLabel;
    private javax.swing.JButton OrderSokBtn;
    private javax.swing.JPanel OrderValjP;
    private javax.swing.JPanel OrderjP;
    private javax.swing.JTextField OrdertF;
    private java.awt.Button button1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextAdress;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextNamn;
    private javax.swing.JTextField jTextTelefon;
    // End of variables declaration//GEN-END:variables
}
