/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Hattmakarsystem;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.plaf.basic.BasicTabbedPaneUI;
import oru.inf.InfException;
/**
 *
 * @author Lucas
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    String Epost;
    int anvandarid;
    DefaultListModel<String> orderlista = new DefaultListModel();
    private JButton[] knappar;
    public GUI() {
        initComponents();
        knappGenerering();
        knappVisning1();
        DisableTabs();
        gomtabs();
        LaddaOrdrar.Allaordrar(jList3,LoggIn.anvanderid);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane8 = new javax.swing.JScrollPane();
        jList6 = new javax.swing.JList<>();
        MenyValjP = new javax.swing.JPanel();
        OrderValjP = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        HuvudPanel = new javax.swing.JTabbedPane();
        KundjP = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        button1 = new java.awt.Button();
        jTextNamn = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextTelefon = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextAdress = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        OrderjP = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jButton8 = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        AntalTB = new javax.swing.JTextField();
        StorlekTB = new javax.swing.JTextField();
        StorlekLabel = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        SpecNamn = new javax.swing.JTextField();
        PrisLabel = new javax.swing.JLabel();
        PrisTB = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        FargTB = new javax.swing.JTextField();
        MaterialTB = new javax.swing.JTextField();
        MaterialLabel = new javax.swing.JLabel();
        Mangdtextbox = new javax.swing.JTextField();
        Mangdlabel = new javax.swing.JLabel();
        Enhet = new javax.swing.JComboBox<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        MaterialList = new javax.swing.JList<>();
        RitningIcon = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane9 = new javax.swing.JScrollPane();
        jList7 = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        AnpassadCB = new javax.swing.JCheckBox();
        jTextField6 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jList5 = new javax.swing.JList<>();
        jTextField2 = new javax.swing.JTextField();
        FraktsedeljP = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jKundTabell = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        DatumJL = new javax.swing.JLabel();
        PrisJL = new javax.swing.JLabel();
        prisJL = new javax.swing.JLabel();
        datumJL = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        HanteraKontojP1 = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtnamn = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jTextID = new javax.swing.JTextField();
        jButton18 = new javax.swing.JButton();
        txtlösenord = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();

        jList6.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane8.setViewportView(jList6);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        MenyValjP.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout MenyValjPLayout = new javax.swing.GroupLayout(MenyValjP);
        MenyValjP.setLayout(MenyValjPLayout);
        MenyValjPLayout.setHorizontalGroup(
            MenyValjPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 194, Short.MAX_VALUE)
        );
        MenyValjPLayout.setVerticalGroup(
            MenyValjPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        OrderValjP.setBackground(new java.awt.Color(51, 51, 51));

        jList3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "344202 - Otoo", "346564 - judith", "458324 - ej tagen" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jList3MouseReleased(evt);
            }
        });
        jScrollPane4.setViewportView(jList3);

        jButton5.setText("jButton5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("jButton6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OrderValjPLayout = new javax.swing.GroupLayout(OrderValjP);
        OrderValjP.setLayout(OrderValjPLayout);
        OrderValjPLayout.setHorizontalGroup(
            OrderValjPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrderValjPLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(OrderValjPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(OrderValjPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(OrderValjPLayout.createSequentialGroup()
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(1, 1, 1))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        OrderValjPLayout.setVerticalGroup(
            OrderValjPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrderValjPLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        HuvudPanel.setBackground(new java.awt.Color(255, 255, 255));
        HuvudPanel.setName(""); // NOI18N
        HuvudPanel.setOpaque(true);

        KundjP.setBackground(new java.awt.Color(255, 255, 255));
        KundjP.setEnabled(false);

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        jLabel1.setText("Sök efter kund epost");

        button1.setLabel("Sök");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Namn");

        jLabel3.setText("Emailadress");

        jLabel4.setText("Telefonnummer");

        jLabel5.setText("Adress");

        jButton1.setText("Gå vidare med vald kund");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Lägg till ny kund och gå vidare");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Ändra kunduppgifter och gå vidare");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout KundjPLayout = new javax.swing.GroupLayout(KundjP);
        KundjP.setLayout(KundjPLayout);
        KundjPLayout.setHorizontalGroup(
            KundjPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KundjPLayout.createSequentialGroup()
                .addGroup(KundjPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(KundjPLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addGroup(KundjPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(KundjPLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(17, 17, 17)
                                .addComponent(jTextTelefon))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, KundjPLayout.createSequentialGroup()
                                .addGroup(KundjPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(40, 40, 40)
                                .addGroup(KundjPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(KundjPLayout.createSequentialGroup()
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jTextNamn)
                                    .addComponent(jTextEmail)))
                            .addGroup(KundjPLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(67, 67, 67)
                                .addComponent(jTextAdress)))
                        .addGap(17, 17, 17))
                    .addGroup(KundjPLayout.createSequentialGroup()
                        .addGap(313, 313, 313)
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(KundjPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(52, 52, 52))
            .addGroup(KundjPLayout.createSequentialGroup()
                .addGroup(KundjPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(KundjPLayout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(jLabel1))
                    .addGroup(KundjPLayout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jButton2))
                    .addGroup(KundjPLayout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(jButton3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        KundjPLayout.setVerticalGroup(
            KundjPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KundjPLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(KundjPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(KundjPLayout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(KundjPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(KundjPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(KundjPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(KundjPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(29, 29, 29))
        );

        HuvudPanel.addTab("Lägg TIll/Välj Kund", KundjP);

        OrderjP.setEnabled(false);

        jScrollPane3.setViewportView(jList2);

        jButton8.setText("Reg order");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jTabbedPane2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane2StateChanged(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setText("Antal hattar");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 6, -1, -1));
        jPanel1.add(AntalTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 35, 94, -1));
        jPanel1.add(StorlekTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 110, 94, -1));

        StorlekLabel.setText("Storlek");
        jPanel1.add(StorlekLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 88, -1, -1));

        EmailLabel.setText("Namn");
        jPanel1.add(EmailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        SpecNamn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SpecNamn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpecNamnActionPerformed(evt);
            }
        });
        jPanel1.add(SpecNamn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 80, 20));

        PrisLabel.setText("Pris");
        jPanel1.add(PrisLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 306, -1, -1));
        jPanel1.add(PrisTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 328, 94, -1));

        jLabel11.setText("Färg");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 142, -1, -1));
        jPanel1.add(FargTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 164, 191, -1));
        jPanel1.add(MaterialTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 191, -1));

        MaterialLabel.setText("Material");
        jPanel1.add(MaterialLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, -1, -1));
        jPanel1.add(Mangdtextbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 119, -1));

        Mangdlabel.setText("Mängd");
        jPanel1.add(Mangdlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, -1, -1));

        Enhet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "cm²", "cm", "m", "m²" }));
        jPanel1.add(Enhet, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, -1, -1));

        jScrollPane5.setViewportView(MaterialList);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(518, 191, 145, -1));

        RitningIcon.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(RitningIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 6, 215, 130));

        jButton12.setText("Lägg till material");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(545, 327, -1, -1));

        jButton13.setText("Lägg till i order");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(518, 6, -1, -1));

        jButton14.setText("Välj ritning");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 99, -1, -1));

        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField3KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 80, -1));

        jScrollPane9.setViewportView(jList7);

        jPanel1.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 80, 70));

        jTabbedPane2.addTab("Special hattar", jPanel1);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        AnpassadCB.setText("anpassa");
        AnpassadCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnpassadCBActionPerformed(evt);
            }
        });

        jTextField6.setEditable(false);

        jTextField8.setEditable(false);

        jTextField9.setEditable(false);

        jButton10.setText("Lägg till i order");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel12.setText("Pris");

        jLabel13.setText("Namn");

        jLabel14.setText("Beskrivning");

        jLabel15.setText("Dekoration");

        jLabel16.setText("Storlek");

        jList5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList5MouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(jList5);

        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(AnpassadCB)
                        .addGap(70, 70, 70))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(332, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton10)
                                .addGap(26, 26, 26))))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel12))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel13))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabel14))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel15))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel16)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AnpassadCB)
                            .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addGap(8, 8, 8)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)))
                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(jButton10)
                        .addGap(59, 59, 59))))
        );

        jTabbedPane2.addTab("Legerförda och anppasade hattar", jPanel2);

        javax.swing.GroupLayout OrderjPLayout = new javax.swing.GroupLayout(OrderjP);
        OrderjP.setLayout(OrderjPLayout);
        OrderjPLayout.setHorizontalGroup(
            OrderjPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OrderjPLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(jButton8)
                .addGap(35, 35, 35))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OrderjPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        OrderjPLayout.setVerticalGroup(
            OrderjPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrderjPLayout.createSequentialGroup()
                .addGroup(OrderjPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OrderjPLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jButton8))
                    .addGroup(OrderjPLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53)
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        HuvudPanel.addTab("Lägg Order", OrderjP);

        FraktsedeljP.setEnabled(false);

        jButton4.setText("Skriv ut");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jKundTabell.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Namn", "Address", "Email", "Telefonnummer", "Typ", "Orderdatum", "Pris", "Totalpris"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jKundTabell.setRowHeight(30);
        jKundTabell.setRowMargin(10);
        jScrollPane2.setViewportView(jKundTabell);

        javax.swing.GroupLayout FraktsedeljPLayout = new javax.swing.GroupLayout(FraktsedeljP);
        FraktsedeljP.setLayout(FraktsedeljPLayout);
        FraktsedeljPLayout.setHorizontalGroup(
            FraktsedeljPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FraktsedeljPLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(34, 34, 34))
            .addGroup(FraktsedeljPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE)
                .addContainerGap())
        );
        FraktsedeljPLayout.setVerticalGroup(
            FraktsedeljPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FraktsedeljPLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 507, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(25, 25, 25))
        );

        HuvudPanel.addTab("fraktsedel", FraktsedeljP);

        jButton9.setLabel("Fraktsedel");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jList4.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "hatt1-storlek-3-material-tygg", "hatt2-", "hatt3" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane6.setViewportView(jList4);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("ordernummer");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("1111111");

        DatumJL.setText("1000-10-10");

        PrisJL.setText("1kr");

        prisJL.setText("Tot pris");

        datumJL.setText("Datum");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(579, Short.MAX_VALUE)
                .addComponent(jButton9)
                .addGap(41, 41, 41))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(datumJL)
                                    .addComponent(DatumJL))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(226, 226, 226)
                                        .addComponent(PrisJL))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addGap(230, 230, 230)
                                        .addComponent(prisJL)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jButton9))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(datumJL)
                            .addComponent(prisJL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DatumJL)
                            .addComponent(PrisJL))))
                .addGap(67, 67, 67))
        );

        HuvudPanel.addTab("Ordrar", jPanel3);

        HanteraKontojP1.setEnabled(false);

        jLabel18.setText("Användarnamn");

        jLabel19.setText("Lösenord");

        jButton15.setText("Lägg till konto");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HanteraKontojP1Layout = new javax.swing.GroupLayout(HanteraKontojP1);
        HanteraKontojP1.setLayout(HanteraKontojP1Layout);
        HanteraKontojP1Layout.setHorizontalGroup(
            HanteraKontojP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HanteraKontojP1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HanteraKontojP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton15)
                    .addGroup(HanteraKontojP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, HanteraKontojP1Layout.createSequentialGroup()
                            .addComponent(jLabel19)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, HanteraKontojP1Layout.createSequentialGroup()
                            .addComponent(jLabel18)
                            .addGap(37, 37, 37)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(431, Short.MAX_VALUE))
        );
        HanteraKontojP1Layout.setVerticalGroup(
            HanteraKontojP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HanteraKontojP1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(HanteraKontojP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(HanteraKontojP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jButton15)
                .addContainerGap(418, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Registrea", HanteraKontojP1);

        jButton16.setText("Spara");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton17.setBackground(new java.awt.Color(255, 51, 51));
        jButton17.setText("Ta bort konto");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jLabel20.setText("Använda Namn");

        jLabel21.setText("Lösenord");

        jLabel22.setText("Ange ditt ID");

        jButton18.setText("Visa");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        txtID.setEditable(false);

        jLabel23.setText("ID:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel20))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jButton17))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtnamn)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jTextID, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jButton18))
                            .addComponent(txtlösenord)
                            .addComponent(txtID))))
                .addContainerGap(334, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jTextID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtlösenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton17)
                    .addComponent(jButton16))
                .addGap(288, 288, 288))
        );

        jTabbedPane1.addTab("Ändra uppgifter", jPanel4);

        HuvudPanel.addTab("Hantera konto", jTabbedPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MenyValjP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(HuvudPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(OrderValjP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(OrderValjP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MenyValjP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(HuvudPanel))
                .addContainerGap())
        );

        HuvudPanel.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jList3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList3MouseReleased
               // TODO add your handling code here:
                   int index = jList3.getSelectedIndex();
                   HuvudPanel.setSelectedIndex(3);
                   if (jList3.getSelectedValue().charAt(0) == '-') {
                       
                       while(jList3.getModel().getElementAt(index).charAt(0) == '-'){
                           index--;
                       }
                       
                   }
                   jLabel9.setText(jList3.getModel().getElementAt(index));
                   OrdrarHattar.fyllOrderLista(jList4,jLabel9,PrisJL,DatumJL);
                   
    }//GEN-LAST:event_jList3MouseReleased

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed

        // Hämtar information om en  baserat på ID som skrivs in
        try {
            String ID = jTextID.getText();
            String fråga = "select * from anvandare where anvandareID = " + ID;
            var svar = Databaskoppling.idb.fetchRow(fråga);

            //Hämtar all information från databasen
            txtID.setText(svar.get("anvandareID"));
            txtnamn.setText(svar.get("namn"));
            txtlösenord.setText(svar.get("losenord"));

            //Hanterar eventuella undantag
        } catch (InfException e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(null, e.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        try {

            String ID2 = Databaskoppling.idb.fetchSingle("SELECT anvandare FROM ordrar WHERE anvandare = '" + txtID.getText() + "'");
            String q2 = "UPDATE ordrar SET anvandare = NULL WHERE anvandare = '" + ID2 + "'";
            Databaskoppling.idb.update(q2);

            String ID = Databaskoppling.idb.fetchSingle("SELECT anvandareID FROM anvandare WHERE anvandareID = '" + txtID.getText() + "'");
            String q1 = "DELETE FROM anvandare WHERE anvandareID = " + ID;
            //String q2 = "DELETE FROM ordrar WHERE  COLUMN  anvandare = " + ID;
            Databaskoppling.idb.delete(q1);

            JOptionPane.showMessageDialog(null, " Användaren är raderad");

        } catch (InfException e) {
            // Hantera eventuella undantag, till exempel visa ett felmeddelande.
            JOptionPane.showMessageDialog(null, "radering misslyckades.");
        }
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        try {
            // Skapar en SQL-fråga för att uppdatera information i databasen
            String fragaTillDatabas = String.format("UPDATE anvandare SET namn = '%s', losenord = '%s' WHERE anvandareID = '%s'", txtnamn.getText(), txtlösenord.getText(), txtID.getText());
            ;
            // Utför SQL UPDATE-operationen genom att skicka frågan till databasen
            Databaskoppling.idb.update(fragaTillDatabas);
            // Visar en bekräftelse att användarens information har uppdaterats
            JOptionPane.showMessageDialog(null, "uppgifter är uppdaterad");
        } catch (InfException e) {
            // Hanterar eventuella databasfel genom att skriva ut felmeddelandet
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        if (!Valideringsklass.emptyTextFields(jTextField5) && !Valideringsklass.emptyTextFields(jTextField10)
        ) {

            try {
                // Vi skapade variabler för att underlätta för oss själva och läsaren
                String nextID = Databaskoppling.idb.getAutoIncrement("anvandare", "anvandareID");
                String namn = jTextField5.getText();
                String losenord = jTextField10.getText();

                ArrayList<String> NamnPaAnvandare;
                NamnPaAnvandare = Databaskoppling.idb.fetchColumn("select namn from anvandare");
                boolean finns = false;
                for (String enAnvandare : NamnPaAnvandare) {
                    if (namn.equals(enAnvandare)) {
                        finns = true;
                        break; // Sluta söka när vi har hittat det önskade resultatet
                    }
                }
                if (!finns) {
                    String SQLFRAGA = "INSERT INTO anvandare (anvandareID, namn, losenord) VALUES ('" + nextID + "', '" + namn + "','" + losenord + "')";

                    Databaskoppling.idb.insert(SQLFRAGA);
                } else {
                    // Talar om att det sökta namnet redan finns och inte går att använda
                    JOptionPane.showMessageDialog(null, "Registreringen gick inte igenom, försök igen!");
                }
                JOptionPane.showMessageDialog(null, "Registrering slutförd!");

            } catch (InfException exc) {
                JOptionPane.showMessageDialog(null, "FEL " + exc.getMessage());
            }

        } else {
            JOptionPane.showMessageDialog(null, "Registreringen gick inte igenom, försök igen!");
        }        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        HuvudPanel.setSelectedIndex(3);
        String[] hej1 = getSelectedGUIOrder();
        Fraktsedel.kundInformation(hej1, jKundTabell);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try {
            JOptionPane.showMessageDialog(null, "Utskrift bekräftad!", "Bekräftelse", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Ett fel uppstod.", "Fel", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTabbedPane2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane2StateChanged
        // TODO add your handling code here:

       
       

    }//GEN-LAST:event_jTabbedPane2StateChanged

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        
        
            String namn = jList5.getSelectedValue();
            String prisStr = jTextField6.getText();
            int pris = Integer.parseInt(prisStr);
            String beskrivning = jTextField9.getText();
            String dekoration = jTextField8.getText();
            String storlekStr = jTextField7.getText();
            int storlek = Integer.parseInt(storlekStr);
            
            LaggTillAnpassade regAnpassad = new LaggTillAnpassade();
            regAnpassad.laggTillAnpassade(namn, pris, dekoration, beskrivning, storlek, AnpassadCB);
            
            regAnpassad.laggTillAnpassadOrder(pris, Epost);
       

        // TODO add your handling code here:fyllComboBox(JComboBox combo)

    }//GEN-LAST:event_jButton10ActionPerformed

    private void AnpassadCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnpassadCBActionPerformed
        // TODO add your handling code here:
        LaggaLagerHatIBestallning.AktivraAnpassad(AnpassadCB,jTextField6,jTextField7,jTextField8,jTextField9);

    }//GEN-LAST:event_AnpassadCBActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        Specbestallning.valjritning(RitningIcon);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        Specbestallning.laggtillspecorder(jList2, Mangdtextbox, MaterialTB, FargTB, MaterialList, Enhet, orderlista, AntalTB, StorlekTB, PrisTB,SpecNamn);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        Specbestallning.laggtillmaterial(Mangdtextbox, MaterialTB,FargTB,MaterialList,Enhet);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void SpecNamnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpecNamnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SpecNamnActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        Specbestallning.registreraorder(jButton8,Epost);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        int selectedIndex = jList1.getSelectedIndex();
        if (selectedIndex != -1) { // Kolla om en rad är vald
            String clickedLine = (String) jList1.getModel().getElementAt(selectedIndex);
            jTextField1.setText(clickedLine);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jList1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            // Konstruera SQL-frågan för att uppdatera kunduppgifter
            String fragaTillDatabas = String.format("UPDATE kund " +
                "SET Namn = '%s', " +
                "telefon = '%s', " +
                "Adress = '%s' " + // Lägg till ytterligare fält efter behov
                "WHERE Email = '%s'",
                jTextNamn.getText(), // Hämta det nya värdet från  GUI-komponent
                jTextTelefon.getText(),
                jTextAdress.getText(), // Lägg till motsvarande fält från  GUI
                jTextEmail.getText()); // Använd e-postadressen för att identifiera kunden att uppdatera

            // Utför SQL UPDATE-operationen genom att skicka frågan till databasen
            Databaskoppling.idb.update(fragaTillDatabas);

            // Visar en bekräftelse att kundens information har uppdaterats
            JOptionPane.showMessageDialog(null, "Kundens uppgifter är uppdaterade");

        } catch (InfException e) {
            // Hanterar eventuella databasfel genom att skriva ut felmeddelandet
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(null, e.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (!Valideringsklass.emptyTextFields(jTextNamn) && !Valideringsklass.emptyTextFields(jTextEmail)
            && !Valideringsklass.emptyTextFields(jTextTelefon) && !Valideringsklass.emptyTextFields(jTextAdress)
        ) {

            try {
                // Vi skapade variabler för att underlätta för oss själva och läsaren
                String nextID = Databaskoppling.idb.getAutoIncrement("kund", "kundid");

                Epost = jTextEmail.getText();
                String telefon = jTextTelefon.getText();
                String namn = jTextNamn.getText();
                String Adress = jTextAdress.getText();

                // int KundID = Integer.parseInt(nextID);

                ArrayList<String> NamnPaKund;
                NamnPaKund = Databaskoppling.idb.fetchColumn("select namn from kund");
                boolean finns = false;
                for (String enKund : NamnPaKund) {
                    if (namn.equals(enKund)) {
                        finns = true;
                        break; // Sluta söka när vi har hittat det önskade resultatet
                    }
                }

                if (!finns) {
                    String SQLFRAGA = "INSERT INTO kund (kundid, adress, email, namn, telefon) VALUES ('" + nextID + "', '" + Adress + "','" + Epost + "','" + namn + "','" + telefon + "')";

                    Databaskoppling.idb.insert(SQLFRAGA);
                } else {
                    // Talar om att det sökta namnet redan finns och inte går att använda
                    JOptionPane.showMessageDialog(null, "Registreringen gick inte igenom, försök igen!");
                }
                JOptionPane.showMessageDialog(null, "Registrering slutförd!");
                HuvudPanel.setSelectedIndex(1);

            } catch (InfException exc) {
                JOptionPane.showMessageDialog(null, "FEL " + exc.getMessage());
            }

        } else {
            JOptionPane.showMessageDialog(null, "Registreringen gick inte igenom, försök igen!");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        HuvudPanel.setSelectedIndex(1);        // TODO add your handling code here:
        Epost = jList1.getSelectedValue();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        try{
            String kundEmail=jTextField1.getText();
            String hamtakund1 = "SELECT * FROM kund WHERE email = '" + kundEmail + "'";
            var hamtaKund=Databaskoppling.idb.fetchRow(hamtakund1)  ;

            jTextEmail.setText(hamtaKund.get("email"));

            jTextTelefon.setText(hamtaKund.get("telefon"));
            jTextNamn.setText(hamtaKund.get("namn"));
            jTextAdress.setText(hamtaKund.get("adress"));

        }
        catch (InfException exc) {
            JOptionPane.showMessageDialog(null, "FEL " + exc.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_button1ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        DefaultListModel<String> listModel = Sok.sok(jTextField1.getText(), "kund", "email");
        jList1.setModel(listModel);
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jList5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList5MouseClicked
        // TODO add your handling code here:
          LaggaLagerHatIBestallning.fyllText(jList5,jTextField6,jTextField8,jTextField9);
    }//GEN-LAST:event_jList5MouseClicked

    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
         DefaultListModel<String> listModel = Sok.sok(jTextField2.getText(), "lagerforda", "namn");
        jList5.setModel(listModel);
    }//GEN-LAST:event_jTextField2KeyReleased

    private void jTextField3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyReleased
        // TODO add your handling code here:
        DefaultListModel<String> listModel = Sok.sok(jTextField3.getText(), "material", "namn");
        jList7.setModel(listModel);
    }//GEN-LAST:event_jTextField3KeyReleased

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        
    }//GEN-LAST:event_jButton6ActionPerformed



    /**
     * @param args the command line arguments
     */
    private void knappGenerering()
    {
        
        int numberoftabs = HuvudPanel.getTabCount();
        knappar = new JButton[numberoftabs];
        for (int i = 0; i < numberoftabs; i++) {  
        final int index = i;
        knappar[i] = new JButton(HuvudPanel.getTitleAt(i));
        knappar[i].addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent e){
               HuvudPanel.setSelectedIndex(index);
            }
        });
            
            
        }
    }
    
    private void DisableTabs()
    {
        for (int i = 0; i < HuvudPanel.getTabCount(); i++) {  
        final int index = i;
        
               HuvudPanel.setEnabledAt(index, false);
            
    }
    }
    
   
    
   public String[] getSelectedGUIOrder()
           {
               
               return jList3.getSelectedValue().trim().split("-");
           }
    
    
    
 private void knappVisning1()
    {
        int height = MenyValjP.getHeight();
    int knapparCount = knappar.length;
    int knappHeight = height / knapparCount;
    int yPosition = (height / knapparCount)/2-20;

    for (JButton button : knappar) {
        MenyValjP.add(button);
        button.setVisible(true);
        button.setSize(150, 40);
        button.setLocation(20, yPosition);

        yPosition += knappHeight;
    }
    }
    
    private void gomtabs()
    {
     HuvudPanel.setUI(new BasicTabbedPaneUI() {       @Override       protected int calculateTabAreaHeight(int tab_placement, int run_count, int max_tab_height) {                         return 0;       }   });
             }   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox AnpassadCB;
    private javax.swing.JTextField AntalTB;
    private javax.swing.JLabel DatumJL;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JComboBox<String> Enhet;
    private javax.swing.JTextField FargTB;
    private javax.swing.JPanel FraktsedeljP;
    private javax.swing.JPanel HanteraKontojP1;
    private javax.swing.JTabbedPane HuvudPanel;
    private javax.swing.JPanel KundjP;
    private javax.swing.JLabel Mangdlabel;
    private javax.swing.JTextField Mangdtextbox;
    private javax.swing.JLabel MaterialLabel;
    private javax.swing.JList<String> MaterialList;
    private javax.swing.JTextField MaterialTB;
    private javax.swing.JPanel MenyValjP;
    private javax.swing.JPanel OrderValjP;
    private javax.swing.JPanel OrderjP;
    private javax.swing.JLabel PrisJL;
    private javax.swing.JLabel PrisLabel;
    private javax.swing.JTextField PrisTB;
    private javax.swing.JLabel RitningIcon;
    private javax.swing.JTextField SpecNamn;
    private javax.swing.JLabel StorlekLabel;
    private javax.swing.JTextField StorlekTB;
    private java.awt.Button button1;
    private javax.swing.JLabel datumJL;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JTable jKundTabell;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JList<String> jList4;
    private javax.swing.JList<String> jList5;
    private javax.swing.JList<String> jList6;
    private javax.swing.JList<String> jList7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextAdress;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField jTextID;
    private javax.swing.JTextField jTextNamn;
    private javax.swing.JTextField jTextTelefon;
    private javax.swing.JLabel prisJL;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtlösenord;
    private javax.swing.JTextField txtnamn;
    // End of variables declaration//GEN-END:variables
}
